### PR TITLE
Update Code for Dependency Changes

### PR DESCRIPTION
**Pull request by mleot**
Primary Changes were to the openpnm function calls to reflect V3.0 and above syntax.

### CODE REVIEW

**Comment by mleot** [comment]
@TomTranter I did a few more tests to see whether the liionpack steps or the OpenPNM steps were causing the slowdown, and I think I've determined it is indeed openpnm taking a long time to solve. I am using their updated methods to obtain the transient solution, but there is an option to use the legacy solver, or use a different integrator. Using the alternate integrator did speed things up by some amount.

**Review by mleot — COMMENTED** [review]
@TomTranter I have determined the cause for poor performance is the lack of methods available for scipy integrators. I believe the problem is stiff, and RK45 is a poor suited integrator for stiff problems. There is already a pull request in the works for adding the other integrators to openpnm: https://github.com/PMEAL/OpenPNM/pull/2880

**Comment by TomTranter** [comment]
@mleot I pinned the version we were using for OpenPNM to avoid these kinds of thing. I haven't kept pace with the developments there and thought going forward we would want to solve the thermal problem and global electrical problem in PyBaMM - I'm not sure it's worth pursuing updating OpenPNM

**Comment by mleot** [comment]
Closing this pull request

**Pull request closed without merging**
